import {MigrationInterface, QueryRunner} from "typeorm";

export class initialize1624434330119 implements MigrationInterface {
    name = 'initialize1624434330119'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP FOREIGN KEY `FK_77afc26dfe5a8633e6ce35eaa44`");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP FOREIGN KEY `FK_e53905ed6170fb65083051881e7`");
        await queryRunner.query("DROP INDEX `IDX_1f3af49b8195937f52d3a66e56` ON `workspacemembers`");
        await queryRunner.query("DROP INDEX `IDX_77afc26dfe5a8633e6ce35eaa4` ON `workspacemembers`");
        await queryRunner.query("DROP INDEX `IDX_3446cc443ce59a7f7ae62acc16` ON `channelmembers`");
        await queryRunner.query("DROP INDEX `IDX_e53905ed6170fb65083051881e` ON `channelmembers`");
        await queryRunner.query("DROP INDEX `UserId` ON `channelmembers`");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP COLUMN `loggedInAt`");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `created_at`");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `updated_at`");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD `loggedInAt` datetime NULL");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP FOREIGN KEY `FK_1f3af49b8195937f52d3a66e566`");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`UserId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP COLUMN `WorkspaceId`");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD `WorkspaceId` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`UserId`, `WorkspaceId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`WorkspaceId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP COLUMN `UserId`");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD `UserId` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`WorkspaceId`, `UserId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP FOREIGN KEY `FK_3446cc443ce59a7f7ae62acc168`");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`UserId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `ChannelId`");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `ChannelId` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`UserId`, `ChannelId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`ChannelId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `UserId`");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `UserId` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`ChannelId`, `UserId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`WorkspaceId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP COLUMN `UserId`");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD `UserId` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`WorkspaceId`, `UserId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`UserId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP COLUMN `WorkspaceId`");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD `WorkspaceId` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`UserId`, `WorkspaceId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`ChannelId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `UserId`");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `UserId` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`ChannelId`, `UserId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`UserId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `ChannelId`");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `ChannelId` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`UserId`, `ChannelId`)");
        await queryRunner.query("CREATE INDEX `UserId` ON `channelmembers` (`UserId`)");
        await queryRunner.query("CREATE INDEX `IDX_1f3af49b8195937f52d3a66e56` ON `workspacemembers` (`UserId`)");
        await queryRunner.query("CREATE INDEX `IDX_77afc26dfe5a8633e6ce35eaa4` ON `workspacemembers` (`WorkspaceId`)");
        await queryRunner.query("CREATE INDEX `IDX_3446cc443ce59a7f7ae62acc16` ON `channelmembers` (`UserId`)");
        await queryRunner.query("CREATE INDEX `IDX_e53905ed6170fb65083051881e` ON `channelmembers` (`ChannelId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD CONSTRAINT `FK_77afc26dfe5a8633e6ce35eaa44` FOREIGN KEY (`WorkspaceId`) REFERENCES `workspaces`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD CONSTRAINT `FK_1f3af49b8195937f52d3a66e566` FOREIGN KEY (`UserId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD CONSTRAINT `FK_e53905ed6170fb65083051881e7` FOREIGN KEY (`ChannelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD CONSTRAINT `FK_3446cc443ce59a7f7ae62acc168` FOREIGN KEY (`UserId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `channelmembers` DROP FOREIGN KEY `FK_3446cc443ce59a7f7ae62acc168`");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP FOREIGN KEY `FK_e53905ed6170fb65083051881e7`");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP FOREIGN KEY `FK_1f3af49b8195937f52d3a66e566`");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP FOREIGN KEY `FK_77afc26dfe5a8633e6ce35eaa44`");
        await queryRunner.query("DROP INDEX `IDX_e53905ed6170fb65083051881e` ON `channelmembers`");
        await queryRunner.query("DROP INDEX `IDX_3446cc443ce59a7f7ae62acc16` ON `channelmembers`");
        await queryRunner.query("DROP INDEX `IDX_77afc26dfe5a8633e6ce35eaa4` ON `workspacemembers`");
        await queryRunner.query("DROP INDEX `IDX_1f3af49b8195937f52d3a66e56` ON `workspacemembers`");
        await queryRunner.query("DROP INDEX `UserId` ON `channelmembers`");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`UserId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `ChannelId`");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `ChannelId` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`ChannelId`, `UserId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`ChannelId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `UserId`");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `UserId` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`ChannelId`, `UserId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`UserId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP COLUMN `WorkspaceId`");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD `WorkspaceId` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`WorkspaceId`, `UserId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`WorkspaceId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP COLUMN `UserId`");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD `UserId` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`WorkspaceId`, `UserId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`ChannelId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `UserId`");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `UserId` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`UserId`, `ChannelId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`UserId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `ChannelId`");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `ChannelId` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD PRIMARY KEY (`UserId`, `ChannelId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD CONSTRAINT `FK_3446cc443ce59a7f7ae62acc168` FOREIGN KEY (`UserId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`WorkspaceId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP COLUMN `UserId`");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD `UserId` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`UserId`, `WorkspaceId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`UserId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP COLUMN `WorkspaceId`");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD `WorkspaceId` varchar(36) NOT NULL");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD PRIMARY KEY (`UserId`, `WorkspaceId`)");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD CONSTRAINT `FK_1f3af49b8195937f52d3a66e566` FOREIGN KEY (`UserId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `updated_at`");
        await queryRunner.query("ALTER TABLE `channelmembers` DROP COLUMN `created_at`");
        await queryRunner.query("ALTER TABLE `workspacemembers` DROP COLUMN `loggedInAt`");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD `loggedInAt` datetime NULL");
        await queryRunner.query("CREATE INDEX `UserId` ON `channelmembers` (`UserId`)");
        await queryRunner.query("CREATE INDEX `IDX_e53905ed6170fb65083051881e` ON `channelmembers` (`ChannelId`)");
        await queryRunner.query("CREATE INDEX `IDX_3446cc443ce59a7f7ae62acc16` ON `channelmembers` (`UserId`)");
        await queryRunner.query("CREATE INDEX `IDX_77afc26dfe5a8633e6ce35eaa4` ON `workspacemembers` (`WorkspaceId`)");
        await queryRunner.query("CREATE INDEX `IDX_1f3af49b8195937f52d3a66e56` ON `workspacemembers` (`UserId`)");
        await queryRunner.query("ALTER TABLE `channelmembers` ADD CONSTRAINT `FK_e53905ed6170fb65083051881e7` FOREIGN KEY (`ChannelId`) REFERENCES `channel`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `workspacemembers` ADD CONSTRAINT `FK_77afc26dfe5a8633e6ce35eaa44` FOREIGN KEY (`WorkspaceId`) REFERENCES `workspaces`(`id`) ON DELETE CASCADE ON UPDATE CASCADE");
    }

}
